# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "562790eb558cbca8458a8c9a0bcf00aa"
name = "app-o-auth"
handle = "app-o-auth"
application_url = "https://bubble-doors-standings-wireless.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "top-bottom-product.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bubble-doors-standings-wireless.trycloudflare.com/auth/callback",
  "https://bubble-doors-standings-wireless.trycloudflare.com/auth/shopify/callback",
  "https://bubble-doors-standings-wireless.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
